- name: Install Apache Artemis
  hosts: localhost
  vars:
    broker_xml: /home/vagrant/artemis_instance/etc/broker.xml
    broker_name: aqs001d
    queues:
      - queue1
      - queue2
      - queue3

  tasks:
    - name: Change broker name
      xml:
        path: "{{ broker_xml }}"
        xpath: /config:configuration/core:core/core:name
        pretty_print: yes
        namespaces:
          config: "urn:activemq"
          core: "urn:activemq:core"
        value: "{{ broker_name }}"

    - name: create queue list
      set_fact:
        #addresses: "{{ addresses | default([]) + [ '<address name='{{ item }}'><anycast><queue name='{{ item }}'></queue></anycast></address>' ] }}"
        addresses: "{{ queues | map("hello") | list }}"
     

    - name: Print queue list
      debug: var=addresses
    # - name: Remove all addresses first
    #   xml:
    #     path: "{{ broker_xml }}"
    #     xpath: /config:configuration/core:core/core:addresses
    #     pretty_print: yes
    #     namespaces:
    #       config: "urn:activemq"
    #       core: "urn:activemq:core"
    #     set_children: []

    - name: Add addresses
      xml:
        path: "{{ broker_xml }}"
        xpath: /config:configuration/core:core/core:addresses
        pretty_print: yes
        input_type: xml
        namespaces:
          config: "urn:activemq"
          core: "urn:activemq:core"
        set_children:
          "{{ addresses }}"
          #"{{ queues }}"
      
          
         
              