- name: Install Apache Artemis
  hosts: localhost
  vars:
    new_version: 2.38.0
    download_url: https://archive.apache.org/dist/activemq/activemq-artemis/{{ new_version }}/apache-artemis-{{ new_version }}-bin.tar.gz
    artemis_instance: /home/vagrant/artemis_instance

  tasks:
    - name: Extract new Apache Artemis version
      unarchive:
        src: "{{ download_url }}"
        dest: /home/vagrant
        remote_src: yes
        owner: vagrant
        group: vagrant
        creates: "/home/vagrant/apache-artemis-{{ new_version }}"

    - name: update Artemis instance
      command: /home/vagrant/apache-artemis-{{ new_version }}/bin/artemis upgrade {{ artemis_instance }}
      become_user: vagrant
      
    # make backup before updating
    # stop the service
    # update the service
    # start the service
